name: docs

on:
  push:
    branches:
      - master
    paths:
      - mkdocs.yml
      - docs/**
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Emacs for Org export
        run: |
          sudo apt-get update
          sudo apt-get install -y emacs-nox
      - name: Generate README.md from Org source
        run: make README.md
      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --only docs
      - name: Install package for API docs (editable)
        run: poetry install --only-root
      - name: Deploy with MkDocs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run mkdocs gh-deploy --force
